// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfEPDj9-gZV1h6MAKIrP6v8fdJvrtH0iU',
    appId: '1:1045515128184:web:458475fb69eb14e55c4c8d',
    messagingSenderId: '1045515128184',
    projectId: 'ethioden-chat',
    authDomain: 'ethioden-chat.firebaseapp.com',
    storageBucket: 'ethioden-chat.firebasestorage.app',
    measurementId: 'G-F5PVDQ63S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc8QBPUN6PIh_ThK4hio4EChCSo-qQ7D4',
    appId: '1:1045515128184:android:adfb02646be5eeea5c4c8d',
    messagingSenderId: '1045515128184',
    projectId: 'ethioden-chat',
    storageBucket: 'ethioden-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdhFviqecOrpstDuO5-9ug7lo8Nm9wQwE',
    appId: '1:1045515128184:ios:3a634df1b3f1056b5c4c8d',
    messagingSenderId: '1045515128184',
    projectId: 'ethioden-chat',
    storageBucket: 'ethioden-chat.firebasestorage.app',
    iosBundleId: 'com.atsed.hiddenMessanger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdhFviqecOrpstDuO5-9ug7lo8Nm9wQwE',
    appId: '1:1045515128184:ios:3a634df1b3f1056b5c4c8d',
    messagingSenderId: '1045515128184',
    projectId: 'ethioden-chat',
    storageBucket: 'ethioden-chat.firebasestorage.app',
    iosBundleId: 'com.atsed.hiddenMessanger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh22ksWYsqf9paDfF5l_8crvItTcdzSu0',
    appId: '1:1045515128184:web:049ea167de43e7d25c4c8d',
    messagingSenderId: '1045515128184',
    projectId: 'ethioden-chat',
    authDomain: 'ethioden-chat.firebaseapp.com',
    storageBucket: 'ethioden-chat.firebasestorage.app',
    measurementId: 'G-WCJMD663Z4',
  );

}